---
# tasks file for sssd_ldap
- name: gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"
    - defaults.yml
  tags: vars

- ansible.builtin.include_tasks: packages.yml

- ansible.builtin.include_tasks: certificates.yml
  when: certificates is defined

- ansible.builtin.include_tasks: sssd.yml

- ansible.builtin.include_tasks: nsswitch.yml
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version is version('8', '<')) or
        (ansible_os_family == "Debian")

- ansible.builtin.include_tasks: pamd.yml

- ansible.builtin.include_tasks: sshd.yml
