---
- name: pamd | add pam_mkhomedir for Debian machines
  copy:
    src: pam_mkhomedir
    dest: /usr/share/pam-configs/sssd_mkhomedir
  when: ansible_os_family == "Debian"
  notify:
    - run pam auth update

- name: pamd | add pam_mkhomedir for RedHat machines
  command: /usr/sbin/authconfig --enablemkhomedir --update
  changed_when: false
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

- name: pamd | enable password auth for RedHat machines
  command: /usr/sbin/authconfig --enablesssdauth --update
  changed_when: false
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

- name: autheselect | enable password auth & mkhomedir for Fedora machines
  command: /usr/bin/authselect select sssd with-mkhomedir --force
  changed_when: false
  when:
    - ansible_distribution == "Fedora"

- name: autheselect | enable oddjobd.service for Fedora machines
  service:
    name: "oddjobd.service"
    state: "started"
    enabled: true
  when:
    - ansible_distribution == "Fedora"
