---
- name: sssd | configure sssd
  become: true
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
    backup: yes
    owner: root
    group: root
  notify:
    - restart sssd

- name: update systemd service unit
  become: true
  community.general.ini_file:
    path: /lib/systemd/system/sssd.service
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  with_items:
    - section: Service
      option: ExecStartPre
      value: "/bin/rm -rf /var/run/sssd.pid || true"
    - section: Service
      option: Restart
      value: always
  when: ansible_service_mgr == 'systemd'
  notify: reload systemd config

- name: sssd | ensure sssd service is enabled
  become: true
  ansible.builtin.service:
    name: sssd
    enabled: true
