---
# handlers file for sssd_ldap
- name: stop sssd
  ansible.builtin.service:
    name: sssd
    state: stopped
  listen: restart sssd

- name: delete sssd cache
  ansible.builtin.file:
    path: "/var/lib/sss/db/{{ item }}"
    state: absent
  with_items:
    - cache_default.ldb
    - config.ldb
    - sssd.ldb
    - timestamps_default.ldb
  listen: restart sssd

- name: start sssd
  ansible.builtin.service:
    name: sssd
    state: started
  listen: restart sssd

- name: run pam auth update
  ansible.builtin.shell: pam-auth-update --package

- name: restart sshd
  ansible.builtin.service:
    name: "{{ sssd_ldap_ssh_service }}"
    state: restarted

- name: reload systemd config
  ansible.builtin.systemd_service:
    name: sssd
    state: restarted
    daemon_reload: yes
  when: ansible_distribution_release != 'trusty'
